#
# Module manifest for module "AzureCodeSigning"
#
# Generated by: James Parsons
#
# Generated on: 8/7/2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = "AzureCodeSigning.psm1"

# Version number of this module.
ModuleVersion = "0.2.24"

# ID used to uniquely identify this module
GUID = "8f802562-6814-4eb2-aa9d-bd1e8fbbab48"

# Author of this module
Author = "James Parsons"

# Company or vendor of this module
CompanyName = "Microsoft"

# Copyright statement for this module
Copyright = "Copyright (c) Microsoft Corporation"

# Description of the functionality provided by this module
Description = "Enables the signing of a set of files with the Azure Code Signing service."

PowerShellVersion = "5.1"

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    "FileFormat\FileFormat.psm1",
    "Metadata\Metadata.psm1",
    "NugetInstall\NugetInstall.psm1",
    "SignTool\SignTool.psm1"
)

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @("Invoke-AzureCodeSigning")

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# List of all modules packaged with this module
ModuleList = @(
    "FileFormat\FileFormat.psm1",
    "Metadata\Metadata.psm1",
    "NugetInstall\NugetInstall.psm1",
    "SignTool\SignTool.psm1"
)

# List of all files packaged with this module
FileList = @(
    "FileFormat\FileFormat.psd1",
    "FileFormat\FileFormat.psm1",
    "Metadata\Metadata.psd1",
    "Metadata\Metadata.psm1",
    "NugetInstall\NugetInstall.psd1",
    "NugetInstall\NugetInstall.psm1",
    "SignTool\SignTool.psd1",
    "SignTool\SignTool.psm1",
    "AzureCodeSigning-help.xml",
    "about_AzureCodeSigning.help.txt"
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            "PSEdition_Core",
            "Windows",
            "Azure",
            "CodeSigning"
        )

        # A URL to an icon representing this module.
        IconUri = "https://raw.githubusercontent.com/Azure/azure-code-signing-action/main/icon.png"

        # A URL to the license for this module.
        LicenseUri = "https://go.microsoft.com/fwlink/?linkid=2237001"
    }

}

}
